import type { KanbanData, Lead, PipelineStage, Tenant } from './types'

// ─────────────────────────────────────────────
// TENANT 1 — CAFÉ COM PAM (design de interiores)
// ─────────────────────────────────────────────

const tenantCafePam: Tenant = {
  id: 'tenant-cafepam-0001',
  name: 'Café com Pam',
  slug: 'cafepam',
}

const stagesCafePam: PipelineStage[] = [
  {
    id: 'stage-cafepam-01',
    tenant_id: 'tenant-cafepam-0001',
    name: 'Novo Lead',
    color: '#6366f1',
    position: 1,
    is_won: false,
    is_lost: false,
  },
  {
    id: 'stage-cafepam-02',
    tenant_id: 'tenant-cafepam-0001',
    name: 'Primeiro Contato',
    color: '#3b82f6',
    position: 2,
    is_won: false,
    is_lost: false,
  },
  {
    id: 'stage-cafepam-03',
    tenant_id: 'tenant-cafepam-0001',
    name: 'Visita Técnica',
    color: '#f59e0b',
    position: 3,
    is_won: false,
    is_lost: false,
  },
  {
    id: 'stage-cafepam-04',
    tenant_id: 'tenant-cafepam-0001',
    name: 'Proposta',
    color: '#8b5cf6',
    position: 4,
    is_won: false,
    is_lost: false,
  },
  {
    id: 'stage-cafepam-05',
    tenant_id: 'tenant-cafepam-0001',
    name: 'Negociação',
    color: '#ec4899',
    position: 5,
    is_won: false,
    is_lost: false,
  },
  {
    id: 'stage-cafepam-06',
    tenant_id: 'tenant-cafepam-0001',
    name: 'Fechado',
    color: '#10b981',
    position: 6,
    is_won: true,
    is_lost: false,
  },
  {
    id: 'stage-cafepam-07',
    tenant_id: 'tenant-cafepam-0001',
    name: 'Perdido',
    color: '#ef4444',
    position: 7,
    is_won: false,
    is_lost: true,
  },
]

const leadsCafePam: Lead[] = [
  // Novo Lead (4 leads)
  {
    id: 'lead-cafepam-001',
    tenant_id: 'tenant-cafepam-0001',
    stage_id: 'stage-cafepam-01',
    name: 'Fernanda Almeida',
    email: 'fernanda.almeida@gmail.com',
    phone: '+55 11 99234-5678',
    company: null,
    source: 'Instagram',
    status: 'new',
    score: 55,
    value: 28000,
    notes: 'Quer reformar sala e dois quartos de apartamento no Itaim Bibi.',
    assigned_to: null,
    last_action_at: null,
    created_at: '2026-03-25T10:00:00Z',
  },
  {
    id: 'lead-cafepam-002',
    tenant_id: 'tenant-cafepam-0001',
    stage_id: 'stage-cafepam-01',
    name: 'Ricardo Monteiro',
    email: 'ricardo.monteiro@outlook.com',
    phone: '+55 21 98876-1234',
    company: null,
    source: 'Site',
    status: 'new',
    score: 40,
    value: 15000,
    notes: 'Busca projeto de home office em apartamento no Leblon, RJ.',
    assigned_to: null,
    last_action_at: null,
    created_at: '2026-03-26T14:30:00Z',
  },
  {
    id: 'lead-cafepam-003',
    tenant_id: 'tenant-cafepam-0001',
    stage_id: 'stage-cafepam-01',
    name: 'Juliana Carvalho',
    email: 'ju.carvalho@hotmail.com',
    phone: '+55 11 97654-3210',
    company: null,
    source: 'Instagram',
    status: 'new',
    score: 60,
    value: 42000,
    notes: 'Casa em Alphaville — quer projeto completo de sala de estar e jantar.',
    assigned_to: null,
    last_action_at: null,
    created_at: '2026-03-27T09:15:00Z',
  },
  {
    id: 'lead-cafepam-004',
    tenant_id: 'tenant-cafepam-0001',
    stage_id: 'stage-cafepam-01',
    name: 'Tiago Neves',
    email: 'tiago.neves@empresa.com.br',
    phone: '+55 11 91234-5678',
    company: 'Neves Advocacia',
    source: 'Indicação',
    status: 'new',
    score: 70,
    value: 55000,
    notes: 'Escritório de advocacia na Faria Lima — reforma completa, prazo 3 meses.',
    assigned_to: null,
    last_action_at: null,
    created_at: '2026-03-28T11:00:00Z',
  },
  // Primeiro Contato (3 leads)
  {
    id: 'lead-cafepam-005',
    tenant_id: 'tenant-cafepam-0001',
    stage_id: 'stage-cafepam-02',
    name: 'Camila Rodrigues',
    email: 'camila.rodrigues@gmail.com',
    phone: '+55 11 98765-4321',
    company: null,
    source: 'Instagram',
    status: 'contacted',
    score: 65,
    value: 32000,
    notes: 'Cobertura em Moema — cozinha americana + varanda gourmet. Retornou ao DM.',
    assigned_to: 'nina',
    last_action_at: '2026-03-24T16:00:00Z',
    created_at: '2026-03-22T08:00:00Z',
  },
  {
    id: 'lead-cafepam-006',
    tenant_id: 'tenant-cafepam-0001',
    stage_id: 'stage-cafepam-02',
    name: 'Paulo Henrique Souza',
    email: 'paulo.souza@gmail.com',
    phone: '+55 21 99123-4567',
    company: null,
    source: 'Site',
    status: 'contacted',
    score: 50,
    value: 18000,
    notes: 'Apartamento no Flamengo, RJ. Dormitório casal + banheiro.',
    assigned_to: 'nina',
    last_action_at: '2026-03-25T10:30:00Z',
    created_at: '2026-03-21T13:00:00Z',
  },
  {
    id: 'lead-cafepam-007',
    tenant_id: 'tenant-cafepam-0001',
    stage_id: 'stage-cafepam-02',
    name: 'Mariana Ferraz',
    email: 'mariana.ferraz@icloud.com',
    phone: '+55 11 95555-6789',
    company: null,
    source: 'Indicação',
    status: 'contacted',
    score: 75,
    value: 65000,
    notes: 'Casa nova em Granja Viana — projeto de interiores completo. Orçamento flexível.',
    assigned_to: 'nina',
    last_action_at: '2026-03-26T09:00:00Z',
    created_at: '2026-03-20T10:00:00Z',
  },
  // Visita Técnica (2 leads)
  {
    id: 'lead-cafepam-008',
    tenant_id: 'tenant-cafepam-0001',
    stage_id: 'stage-cafepam-03',
    name: 'Beatriz Lima',
    email: 'beatriz.lima@yahoo.com.br',
    phone: '+55 11 94321-8765',
    company: null,
    source: 'Instagram',
    status: 'qualified',
    score: 80,
    value: 48000,
    notes: 'Visita agendada para 01/04. Apê de 120m² no Paraíso. Ambientes: sala, quartos e banheiros.',
    assigned_to: 'nina',
    last_action_at: '2026-03-27T14:00:00Z',
    created_at: '2026-03-15T09:00:00Z',
  },
  {
    id: 'lead-cafepam-009',
    tenant_id: 'tenant-cafepam-0001',
    stage_id: 'stage-cafepam-03',
    name: 'Rodrigo Teixeira',
    email: 'rteixeira@gmail.com',
    phone: '+55 11 93456-7890',
    company: 'Studio RT Design',
    source: 'Indicação',
    status: 'qualified',
    score: 85,
    value: 85000,
    notes: 'Loft comercial na Vila Madalena para estúdio criativo. Visita feita em 25/03.',
    assigned_to: 'nina',
    last_action_at: '2026-03-25T17:00:00Z',
    created_at: '2026-03-10T11:00:00Z',
  },
  // Proposta (1 lead)
  {
    id: 'lead-cafepam-010',
    tenant_id: 'tenant-cafepam-0001',
    stage_id: 'stage-cafepam-04',
    name: 'Luciana Prado',
    email: 'luciana.prado@gmail.com',
    phone: '+55 11 98001-2345',
    company: null,
    source: 'Indicação',
    status: 'proposal',
    score: 88,
    value: 73000,
    notes: 'Proposta enviada em 26/03. Aguardando retorno. Casa de 200m² em Cotia.',
    assigned_to: 'nina',
    last_action_at: '2026-03-26T12:00:00Z',
    created_at: '2026-03-05T08:00:00Z',
  },
  // Fechado (1 lead)
  {
    id: 'lead-cafepam-011',
    tenant_id: 'tenant-cafepam-0001',
    stage_id: 'stage-cafepam-06',
    name: 'Ana Paula Martins',
    email: 'anapaula.martins@gmail.com',
    phone: '+55 11 97890-1234',
    company: null,
    source: 'Instagram',
    status: 'won',
    score: 95,
    value: 62000,
    notes: 'Contrato assinado em 20/03. Projeto de 3 dormitórios em São Paulo — início em abril.',
    assigned_to: 'nina',
    last_action_at: '2026-03-20T15:00:00Z',
    created_at: '2026-02-28T10:00:00Z',
  },
  // Perdido (1 lead)
  {
    id: 'lead-cafepam-012',
    tenant_id: 'tenant-cafepam-0001',
    stage_id: 'stage-cafepam-07',
    name: 'Carlos Eduardo Braga',
    email: 'carlos.braga@hotmail.com',
    phone: '+55 11 96543-2109',
    company: null,
    source: 'Site',
    status: 'lost',
    score: 20,
    value: 8000,
    notes: 'Optou por arquiteto local com menor custo. Orçamento abaixo do mínimo de projeto.',
    assigned_to: null,
    last_action_at: '2026-03-18T11:00:00Z',
    created_at: '2026-03-10T14:00:00Z',
  },
]

export const cafePamData: KanbanData = {
  tenant: tenantCafePam,
  stages: stagesCafePam,
  leads: leadsCafePam,
}

// ─────────────────────────────────────────────
// TENANT 2 — JUREMA BROKERS (imobiliária João Pessoa)
// ─────────────────────────────────────────────

const tenantJurema: Tenant = {
  id: 'tenant-jurema-0001',
  name: 'Jurema Brokers',
  slug: 'jurema-brokers',
}

const stagesJurema: PipelineStage[] = [
  {
    id: 'stage-jurema-01',
    tenant_id: 'tenant-jurema-0001',
    name: 'Interessado',
    color: '#6366f1',
    position: 1,
    is_won: false,
    is_lost: false,
  },
  {
    id: 'stage-jurema-02',
    tenant_id: 'tenant-jurema-0001',
    name: 'Qualificado',
    color: '#3b82f6',
    position: 2,
    is_won: false,
    is_lost: false,
  },
  {
    id: 'stage-jurema-03',
    tenant_id: 'tenant-jurema-0001',
    name: 'Visita ao Imóvel',
    color: '#f59e0b',
    position: 3,
    is_won: false,
    is_lost: false,
  },
  {
    id: 'stage-jurema-04',
    tenant_id: 'tenant-jurema-0001',
    name: 'Proposta Enviada',
    color: '#8b5cf6',
    position: 4,
    is_won: false,
    is_lost: false,
  },
  {
    id: 'stage-jurema-05',
    tenant_id: 'tenant-jurema-0001',
    name: 'Em Negociação',
    color: '#ec4899',
    position: 5,
    is_won: false,
    is_lost: false,
  },
  {
    id: 'stage-jurema-06',
    tenant_id: 'tenant-jurema-0001',
    name: 'Contrato Assinado',
    color: '#10b981',
    position: 6,
    is_won: true,
    is_lost: false,
  },
  {
    id: 'stage-jurema-07',
    tenant_id: 'tenant-jurema-0001',
    name: 'Perdido',
    color: '#ef4444',
    position: 7,
    is_won: false,
    is_lost: true,
  },
]

const leadsJurema: Lead[] = [
  // Interessado (4 leads)
  {
    id: 'lead-jurema-001',
    tenant_id: 'tenant-jurema-0001',
    stage_id: 'stage-jurema-01',
    name: 'Marcos Vinícius Santos',
    email: 'marcosvinicius.santos@gmail.com',
    phone: '+55 83 99876-5432',
    company: null,
    source: 'Zap Imóveis',
    status: 'new',
    score: 45,
    value: 320000,
    notes: 'Busca apartamento 2 quartos no Bessa ou Cabo Branco. Financiamento CEF.',
    assigned_to: null,
    last_action_at: null,
    created_at: '2026-03-26T08:00:00Z',
  },
  {
    id: 'lead-jurema-002',
    tenant_id: 'tenant-jurema-0001',
    stage_id: 'stage-jurema-01',
    name: 'Patrícia Gonçalves',
    email: 'patricia.goncalves@hotmail.com',
    phone: '+55 83 98765-1234',
    company: null,
    source: 'OLX',
    status: 'new',
    score: 35,
    value: 195000,
    notes: 'Casa térrea em Mangabeira ou Bancários. Até R$ 200 mil. Minha Casa Minha Vida.',
    assigned_to: null,
    last_action_at: null,
    created_at: '2026-03-27T09:30:00Z',
  },
  {
    id: 'lead-jurema-003',
    tenant_id: 'tenant-jurema-0001',
    stage_id: 'stage-jurema-01',
    name: 'Felipe Araújo',
    email: 'felipe.araujo@empresa.pb.gov.br',
    phone: '+55 83 91234-5678',
    company: 'Governo do Estado PB',
    source: 'Indicação',
    status: 'new',
    score: 70,
    value: 580000,
    notes: 'Servidor público, busca cobertura ou apê 3 quartos no Altiplano. À vista ou FGTS.',
    assigned_to: null,
    last_action_at: null,
    created_at: '2026-03-28T10:00:00Z',
  },
  {
    id: 'lead-jurema-004',
    tenant_id: 'tenant-jurema-0001',
    stage_id: 'stage-jurema-01',
    name: 'Renata Bezerra',
    email: 'renata.bezerra@gmail.com',
    phone: '+55 83 97654-3210',
    company: null,
    source: 'Instagram',
    status: 'new',
    score: 50,
    value: 380000,
    notes: 'Viu anúncio do empreendimento Garden Bessa. Quer planta de 3 quartos com suíte.',
    assigned_to: null,
    last_action_at: null,
    created_at: '2026-03-28T14:00:00Z',
  },
  // Qualificado (2 leads)
  {
    id: 'lead-jurema-005',
    tenant_id: 'tenant-jurema-0001',
    stage_id: 'stage-jurema-02',
    name: 'Kleber Morais',
    email: 'kleber.morais@yahoo.com.br',
    phone: '+55 83 99001-2345',
    company: null,
    source: 'Zap Imóveis',
    status: 'qualified',
    score: 72,
    value: 450000,
    notes: 'Aprovado em financiamento Bradesco até R$ 450 mil. Prefere Tambaú ou Manaíra.',
    assigned_to: 'luana',
    last_action_at: '2026-03-25T11:00:00Z',
    created_at: '2026-03-18T09:00:00Z',
  },
  {
    id: 'lead-jurema-006',
    tenant_id: 'tenant-jurema-0001',
    stage_id: 'stage-jurema-02',
    name: 'Suely Cavalcanti',
    email: 'suely.cavalcanti@gmail.com',
    phone: '+55 83 98543-6789',
    company: 'Cavalcanti & Filhos Ltda',
    source: 'Indicação',
    status: 'qualified',
    score: 80,
    value: 750000,
    notes: 'Empresária, busca imóvel para investimento. Prefere cobertura ou sala comercial no centro.',
    assigned_to: 'luana',
    last_action_at: '2026-03-26T10:00:00Z',
    created_at: '2026-03-14T13:00:00Z',
  },
  // Visita ao Imóvel (1 lead)
  {
    id: 'lead-jurema-007',
    tenant_id: 'tenant-jurema-0001',
    stage_id: 'stage-jurema-03',
    name: 'Anderson Lima',
    email: 'anderson.lima@gmail.com',
    phone: '+55 83 96789-0123',
    company: null,
    source: 'Zap Imóveis',
    status: 'qualified',
    score: 78,
    value: 280000,
    notes: 'Visitou apê de 2 quartos no Jardim Oceania em 27/03. Gostou mas quer ver mais um.',
    assigned_to: 'luana',
    last_action_at: '2026-03-27T15:00:00Z',
    created_at: '2026-03-12T10:00:00Z',
  },
  // Proposta Enviada (1 lead)
  {
    id: 'lead-jurema-008',
    tenant_id: 'tenant-jurema-0001',
    stage_id: 'stage-jurema-04',
    name: 'Gisele Nascimento',
    email: 'gisele.nascimento@icloud.com',
    phone: '+55 83 95432-1098',
    company: null,
    source: 'Instagram',
    status: 'proposal',
    score: 83,
    value: 480000,
    notes: 'Proposta de cobertura no Bessa enviada em 25/03. Aguardando aprovação do marido.',
    assigned_to: 'luana',
    last_action_at: '2026-03-25T16:00:00Z',
    created_at: '2026-03-07T08:00:00Z',
  },
  // Contrato Assinado (1 lead)
  {
    id: 'lead-jurema-009',
    tenant_id: 'tenant-jurema-0001',
    stage_id: 'stage-jurema-06',
    name: 'Davi Oliveira',
    email: 'davi.oliveira@gmail.com',
    phone: '+55 83 99321-6547',
    company: null,
    source: 'Indicação',
    status: 'won',
    score: 96,
    value: 850000,
    notes: 'Compra de penthouse em Tambaú. Contrato assinado em 15/03. Escritura prevista para maio.',
    assigned_to: 'luana',
    last_action_at: '2026-03-15T14:00:00Z',
    created_at: '2026-02-20T09:00:00Z',
  },
  // Perdido (1 lead)
  {
    id: 'lead-jurema-010',
    tenant_id: 'tenant-jurema-0001',
    stage_id: 'stage-jurema-07',
    name: 'Tatiane Farias',
    email: 'tatiane.farias@hotmail.com',
    phone: '+55 83 98210-4321',
    company: null,
    source: 'OLX',
    status: 'lost',
    score: 22,
    value: 180000,
    notes: 'Comprou imóvel diretamente com construtora. Não quis negociar por corretor.',
    assigned_to: null,
    last_action_at: '2026-03-19T09:00:00Z',
    created_at: '2026-03-05T11:00:00Z',
  },
]

export const juremaData: KanbanData = {
  tenant: tenantJurema,
  stages: stagesJurema,
  leads: leadsJurema,
}

// ─────────────────────────────────────────────
// Export consolidado de todos os tenants
// ─────────────────────────────────────────────

export const allTenantsData: KanbanData[] = [cafePamData, juremaData]
