import type { KanbanData, Lead, PipelineStage, Tenant } from './types'

// ─────────────────────────────────────────────
// TENANT 1 — CAFÉ COM PAM (design de interiores)
// Fluxo YZIHUB: lead chega qualificado pela IA
// ─────────────────────────────────────────────

const tenantCafePam: Tenant = {
  id: 'tenant-cafepam-0001',
  name: 'Café com Pam',
  slug: 'cafepam',
}

const stagesCafePam: PipelineStage[] = [
  {
    id: 'stage-cafepam-01',
    tenant_id: 'tenant-cafepam-0001',
    name: '🔥 Novo Lead',
    color: '#6366f1',
    position: 1,
    is_won: false,
    is_lost: false,
  },
  {
    id: 'stage-cafepam-02',
    tenant_id: 'tenant-cafepam-0001',
    name: '📅 Agendado',
    color: '#f59e0b',
    position: 2,
    is_won: false,
    is_lost: false,
  },
  {
    id: 'stage-cafepam-03',
    tenant_id: 'tenant-cafepam-0001',
    name: '💬 Em Atendimento',
    color: '#8b5cf6',
    position: 3,
    is_won: false,
    is_lost: false,
  },
  {
    id: 'stage-cafepam-04',
    tenant_id: 'tenant-cafepam-0001',
    name: '💳 Pagamento Confirmado',
    color: '#10b981',
    position: 4,
    is_won: false,
    is_lost: false,
  },
  {
    id: 'stage-cafepam-05',
    tenant_id: 'tenant-cafepam-0001',
    name: '✅ Concluído',
    color: '#059669',
    position: 5,
    is_won: true,
    is_lost: false,
  },
  {
    id: 'stage-cafepam-06',
    tenant_id: 'tenant-cafepam-0001',
    name: '❌ Cancelado',
    color: '#ef4444',
    position: 6,
    is_won: false,
    is_lost: true,
  },
]

const leadsCafePam: Lead[] = [
  // 🔥 Novo Lead (4 leads)
  {
    id: 'lead-cafepam-001',
    tenant_id: 'tenant-cafepam-0001',
    stage_id: 'stage-cafepam-01',
    name: 'Fernanda Almeida',
    email: 'fernanda.almeida@gmail.com',
    phone: '+55 11 99234-5678',
    company: null,
    source: 'Instagram',
    status: 'new',
    score: 78,
    value: 28000,
    notes: 'Lead qualificado pela IA Nina. Quer reformar sala e dois quartos no Itaim Bibi.',
    assigned_to: null,
    last_action_at: null,
    created_at: '2026-03-25T10:00:00Z',
  },
  {
    id: 'lead-cafepam-002',
    tenant_id: 'tenant-cafepam-0001',
    stage_id: 'stage-cafepam-01',
    name: 'Ricardo Monteiro',
    email: 'ricardo.monteiro@outlook.com',
    phone: '+55 21 98876-1234',
    company: null,
    source: 'Site',
    status: 'new',
    score: 65,
    value: 15000,
    notes: 'Home office no Leblon. Qualificado via n8n.',
    assigned_to: null,
    last_action_at: null,
    created_at: '2026-03-26T14:30:00Z',
  },
  {
    id: 'lead-cafepam-003',
    tenant_id: 'tenant-cafepam-0001',
    stage_id: 'stage-cafepam-01',
    name: 'Juliana Carvalho',
    email: 'ju.carvalho@hotmail.com',
    phone: '+55 11 97654-3210',
    company: null,
    source: 'Instagram',
    status: 'new',
    score: 82,
    value: 42000,
    notes: 'Casa em Alphaville — sala completa. IA confirmou interesse e orçamento.',
    assigned_to: null,
    last_action_at: null,
    created_at: '2026-03-27T09:15:00Z',
  },
  {
    id: 'lead-cafepam-004',
    tenant_id: 'tenant-cafepam-0001',
    stage_id: 'stage-cafepam-01',
    name: 'Tiago Neves',
    email: 'tiago.neves@empresa.com.br',
    phone: '+55 11 91234-5678',
    company: 'Neves Advocacia',
    source: 'Indicação',
    status: 'new',
    score: 90,
    value: 55000,
    notes: 'Escritório na Faria Lima. Prazo 3 meses. Orçamento aprovado pela IA.',
    assigned_to: null,
    last_action_at: null,
    created_at: '2026-03-28T11:00:00Z',
  },
  // 📞 Contato (3 leads)
  {
    id: 'lead-cafepam-005',
    tenant_id: 'tenant-cafepam-0001',
    stage_id: 'stage-cafepam-02',
    name: 'Camila Rodrigues',
    email: 'camila.rodrigues@gmail.com',
    phone: '+55 11 98765-4321',
    company: null,
    source: 'Instagram',
    status: 'contacted',
    score: 75,
    value: 32000,
    notes: 'Cobertura em Moema. Time entrou em contato em 24/03.',
    assigned_to: 'nina',
    last_action_at: '2026-03-24T16:00:00Z',
    created_at: '2026-03-22T08:00:00Z',
  },
  {
    id: 'lead-cafepam-006',
    tenant_id: 'tenant-cafepam-0001',
    stage_id: 'stage-cafepam-02',
    name: 'Paulo Henrique Souza',
    email: 'paulo.souza@gmail.com',
    phone: '+55 21 99123-4567',
    company: null,
    source: 'Site',
    status: 'contacted',
    score: 70,
    value: 18000,
    notes: 'Apto no Flamengo. Aguardando confirmação de horário para reunião.',
    assigned_to: 'nina',
    last_action_at: '2026-03-25T10:30:00Z',
    created_at: '2026-03-21T13:00:00Z',
  },
  {
    id: 'lead-cafepam-007',
    tenant_id: 'tenant-cafepam-0001',
    stage_id: 'stage-cafepam-02',
    name: 'Mariana Ferraz',
    email: 'mariana.ferraz@icloud.com',
    phone: '+55 11 95555-6789',
    company: null,
    source: 'Indicação',
    status: 'contacted',
    score: 88,
    value: 65000,
    notes: 'Casa em Granja Viana — projeto completo. Quer reunião presencial.',
    assigned_to: 'nina',
    last_action_at: '2026-03-26T09:00:00Z',
    created_at: '2026-03-20T10:00:00Z',
  },
  // 📅 Reunião (2 leads)
  {
    id: 'lead-cafepam-008',
    tenant_id: 'tenant-cafepam-0001',
    stage_id: 'stage-cafepam-03',
    name: 'Beatriz Lima',
    email: 'beatriz.lima@yahoo.com.br',
    phone: '+55 11 94321-8765',
    company: null,
    source: 'Instagram',
    status: 'meeting',
    score: 85,
    value: 48000,
    notes: 'Reunião feita em 01/04. Apê de 120m² no Paraíso. Aguardando proposta.',
    assigned_to: 'nina',
    last_action_at: '2026-03-29T14:00:00Z',
    created_at: '2026-03-15T09:00:00Z',
  },
  {
    id: 'lead-cafepam-009',
    tenant_id: 'tenant-cafepam-0001',
    stage_id: 'stage-cafepam-03',
    name: 'Rodrigo Teixeira',
    email: 'rteixeira@gmail.com',
    phone: '+55 11 93456-7890',
    company: 'Studio RT Design',
    source: 'Indicação',
    status: 'meeting',
    score: 91,
    value: 85000,
    notes: 'Loft na Vila Madalena. Reunião em 25/03. Pronto para proposta.',
    assigned_to: 'nina',
    last_action_at: '2026-03-25T17:00:00Z',
    created_at: '2026-03-10T11:00:00Z',
  },
  // 💰 Proposta (1 lead)
  {
    id: 'lead-cafepam-010',
    tenant_id: 'tenant-cafepam-0001',
    stage_id: 'stage-cafepam-04',
    name: 'Luciana Prado',
    email: 'luciana.prado@gmail.com',
    phone: '+55 11 98001-2345',
    company: null,
    source: 'Indicação',
    status: 'proposal',
    score: 93,
    value: 73000,
    notes: 'Proposta de R$ 73k enviada em 26/03. Aguardando aprovação. Casa de 200m² em Cotia.',
    assigned_to: 'nina',
    last_action_at: '2026-03-26T12:00:00Z',
    created_at: '2026-03-05T08:00:00Z',
  },
  // ✅ Fechado (1 lead)
  {
    id: 'lead-cafepam-011',
    tenant_id: 'tenant-cafepam-0001',
    stage_id: 'stage-cafepam-05',
    name: 'Ana Paula Martins',
    email: 'anapaula.martins@gmail.com',
    phone: '+55 11 97890-1234',
    company: null,
    source: 'Instagram',
    status: 'won',
    score: 98,
    value: 62000,
    notes: 'Contrato assinado em 20/03. Projeto de 3 dormitórios — início em abril.',
    assigned_to: 'nina',
    last_action_at: '2026-03-20T15:00:00Z',
    created_at: '2026-02-28T10:00:00Z',
  },
  // ❌ Perdido (1 lead)
  {
    id: 'lead-cafepam-012',
    tenant_id: 'tenant-cafepam-0001',
    stage_id: 'stage-cafepam-06',
    name: 'Carlos Eduardo Braga',
    email: 'carlos.braga@hotmail.com',
    phone: '+55 11 96543-2109',
    company: null,
    source: 'Site',
    status: 'lost',
    score: 20,
    value: 8000,
    notes: 'Optou por arquiteto local com menor custo.',
    assigned_to: null,
    last_action_at: '2026-03-18T11:00:00Z',
    created_at: '2026-03-10T14:00:00Z',
  },
]

export const cafePamData: KanbanData = {
  tenant: tenantCafePam,
  stages: stagesCafePam,
  leads: leadsCafePam,
}
