import type { ControlDashboardData, ControlTenant, Job, ActionLog } from './types'

// Base timestamp: 2026-03-29T12:00:00Z
const BASE = '2026-03-29T12:00:00Z'
const ts = (offsetMinutes: number): string => {
  const d = new Date(BASE)
  d.setMinutes(d.getMinutes() + offsetMinutes)
  return d.toISOString()
}
const daysAgo = (days: number): string => {
  const d = new Date(BASE)
  d.setDate(d.getDate() - days)
  return d.toISOString()
}

// ─── TENANTS ────────────────────────────────────────────────────────────────

const tenantCafePam: ControlTenant = {
  id: 'tenant-cafepam-0001',
  name: 'Café com Pam',
  slug: 'cafepam',
  plan: 'growth',
  status: 'active',
  system_prompt: null,
  knowledge_rag_xml: null,
  projects: [
    {
      id: 'proj-cafepam-crm-001',
      tenant_id: 'tenant-cafepam-0001',
      name: 'CRM Café com Pam',
      type: 'crm',
      status: 'active',
      agent_name: 'Nina',
      agent_phone: '+5511999990001',
    },
    {
      id: 'proj-cafepam-sdr-001',
      tenant_id: 'tenant-cafepam-0001',
      name: 'SDR Café com Pam',
      type: 'sdr',
      status: 'active',
      agent_name: 'Nina',
      agent_phone: '+5511999990001',
    },
    {
      id: 'proj-cafepam-ia-001',
      tenant_id: 'tenant-cafepam-0001',
      name: 'IA Onboarding Café com Pam',
      type: 'ia_onboarding',
      status: 'active',
      agent_name: 'Nina',
      agent_phone: '+5511999990001',
    },
  ],
  stats: {
    total_leads: 12,
    active_leads: 8,
    won_leads: 2,
    pipeline_value: 340000,
    conversion_rate: 16.7,
  },
  created_at: daysAgo(30),
}

const tenantJurema: ControlTenant = {
  id: 'tenant-jurema-0001',
  name: 'Jurema Brokers',
  slug: 'jurema',
  plan: 'growth',
  status: 'active',
  system_prompt: null,
  knowledge_rag_xml: null,
  projects: [
    {
      id: 'proj-jurema-crm-001',
      tenant_id: 'tenant-jurema-0001',
      name: 'CRM Jurema Brokers',
      type: 'crm',
      status: 'active',
      agent_name: 'Luana',
      agent_phone: '+5583999990002',
    },
    {
      id: 'proj-jurema-sdr-001',
      tenant_id: 'tenant-jurema-0001',
      name: 'SDR Jurema Brokers',
      type: 'sdr',
      status: 'active',
      agent_name: 'Luana',
      agent_phone: '+5583999990002',
    },
    {
      id: 'proj-jurema-radar-001',
      tenant_id: 'tenant-jurema-0001',
      name: 'Radar Jurema Brokers',
      type: 'radar',
      status: 'active',
      agent_name: null,
      agent_phone: null,
    },
  ],
  stats: {
    total_leads: 10,
    active_leads: 7,
    won_leads: 1,
    pipeline_value: 2850000,
    conversion_rate: 10,
  },
  created_at: daysAgo(45),
}

const tenantNexus: ControlTenant = {
  id: 'tenant-nexus-0001',
  name: 'Nexus Consultoria',
  slug: 'nexus',
  plan: 'starter',
  status: 'active',
  system_prompt: null,
  knowledge_rag_xml: null,
  projects: [
    {
      id: 'proj-nexus-crm-001',
      tenant_id: 'tenant-nexus-0001',
      name: 'CRM Nexus Consultoria',
      type: 'crm',
      status: 'provisioning',
      agent_name: null,
      agent_phone: null,
    },
  ],
  stats: {
    total_leads: 3,
    active_leads: 3,
    won_leads: 0,
    pipeline_value: 45000,
    conversion_rate: 0,
  },
  created_at: daysAgo(5),
}

// ─── RECENT JOBS (10) ────────────────────────────────────────────────────────

const recentJobs: Job[] = [
  {
    id: 'job-001',
    tenant_id: 'tenant-cafepam-0001',
    tenant_name: 'Café com Pam',
    lead_id: 'lead-cafepam-001',
    lead_name: 'Ana Lima',
    action: 'qualify',
    status: 'done',
    attempts: 1,
    error: null,
    scheduled_at: ts(-120),
    started_at: ts(-119),
    finished_at: ts(-118),
    created_at: ts(-120),
  },
  {
    id: 'job-002',
    tenant_id: 'tenant-jurema-0001',
    tenant_name: 'Jurema Brokers',
    lead_id: 'lead-jurema-001',
    lead_name: 'João Ferreira',
    action: 'send_proposal',
    status: 'done',
    attempts: 1,
    error: null,
    scheduled_at: ts(-110),
    started_at: ts(-109),
    finished_at: ts(-107),
    created_at: ts(-110),
  },
  {
    id: 'job-003',
    tenant_id: 'tenant-cafepam-0001',
    tenant_name: 'Café com Pam',
    lead_id: 'lead-cafepam-002',
    lead_name: 'Carla Mendes',
    action: 'schedule',
    status: 'done',
    attempts: 1,
    error: null,
    scheduled_at: ts(-100),
    started_at: ts(-99),
    finished_at: ts(-97),
    created_at: ts(-100),
  },
  {
    id: 'job-004',
    tenant_id: 'tenant-jurema-0001',
    tenant_name: 'Jurema Brokers',
    lead_id: 'lead-jurema-002',
    lead_name: 'Marcos Viana',
    action: 'ai_takeover',
    status: 'done',
    attempts: 1,
    error: null,
    scheduled_at: ts(-90),
    started_at: ts(-89),
    finished_at: ts(-87),
    created_at: ts(-90),
  },
  {
    id: 'job-005',
    tenant_id: 'tenant-nexus-0001',
    tenant_name: 'Nexus Consultoria',
    lead_id: 'lead-nexus-001',
    lead_name: 'Pedro Alves',
    action: 'qualify',
    status: 'failed',
    attempts: 3,
    error: 'WhatsApp offline — Evolution API timeout',
    scheduled_at: ts(-80),
    started_at: ts(-79),
    finished_at: ts(-75),
    created_at: ts(-80),
  },
  {
    id: 'job-006',
    tenant_id: 'tenant-cafepam-0001',
    tenant_name: 'Café com Pam',
    lead_id: 'lead-cafepam-003',
    lead_name: 'Beatriz Santos',
    action: 'send_proposal',
    status: 'processing',
    attempts: 1,
    error: null,
    scheduled_at: ts(-60),
    started_at: ts(-58),
    finished_at: null,
    created_at: ts(-60),
  },
  {
    id: 'job-007',
    tenant_id: 'tenant-jurema-0001',
    tenant_name: 'Jurema Brokers',
    lead_id: 'lead-jurema-003',
    lead_name: 'Fernanda Costa',
    action: 'schedule',
    status: 'processing',
    attempts: 1,
    error: null,
    scheduled_at: ts(-40),
    started_at: ts(-38),
    finished_at: null,
    created_at: ts(-40),
  },
  {
    id: 'job-008',
    tenant_id: 'tenant-nexus-0001',
    tenant_name: 'Nexus Consultoria',
    lead_id: 'lead-nexus-002',
    lead_name: 'Ricardo Lima',
    action: 'qualify',
    status: 'pending',
    attempts: 0,
    error: null,
    scheduled_at: ts(-20),
    started_at: null,
    finished_at: null,
    created_at: ts(-20),
  },
  {
    id: 'job-009',
    tenant_id: 'tenant-cafepam-0001',
    tenant_name: 'Café com Pam',
    lead_id: 'lead-cafepam-004',
    lead_name: 'Lucas Rocha',
    action: 'ai_takeover',
    status: 'pending',
    attempts: 0,
    error: null,
    scheduled_at: ts(-10),
    started_at: null,
    finished_at: null,
    created_at: ts(-10),
  },
  {
    id: 'job-010',
    tenant_id: 'tenant-jurema-0001',
    tenant_name: 'Jurema Brokers',
    lead_id: 'lead-jurema-004',
    lead_name: 'Sofia Barbosa',
    action: 'send_proposal',
    status: 'done',
    attempts: 1,
    error: null,
    scheduled_at: ts(-5),
    started_at: ts(-4),
    finished_at: ts(-2),
    created_at: ts(-5),
  },
]

// ─── RECENT LOGS (15) ────────────────────────────────────────────────────────

const recentLogs: ActionLog[] = [
  {
    id: 'log-001',
    tenant_id: 'tenant-cafepam-0001',
    tenant_name: 'Café com Pam',
    lead_id: 'lead-cafepam-001',
    lead_name: 'Ana Lima',
    job_id: 'job-001',
    action: 'qualify',
    channel: 'n8n',
    summary: 'Lead Ana Lima qualificada via IA — score 82',
    created_at: ts(-118),
  },
  {
    id: 'log-002',
    tenant_id: 'tenant-jurema-0001',
    tenant_name: 'Jurema Brokers',
    lead_id: 'lead-jurema-001',
    lead_name: 'João Ferreira',
    job_id: 'job-002',
    action: 'send_proposal',
    channel: 'whatsapp',
    summary: 'Proposta PDF enviada para João Ferreira via WhatsApp',
    created_at: ts(-107),
  },
  {
    id: 'log-003',
    tenant_id: 'tenant-cafepam-0001',
    tenant_name: 'Café com Pam',
    lead_id: 'lead-cafepam-001',
    lead_name: 'Ana Lima',
    job_id: null,
    action: 'view_lead',
    channel: 'web',
    summary: 'Eric visualizou lead Ana Lima no painel CONTROL',
    created_at: ts(-115),
  },
  {
    id: 'log-004',
    tenant_id: 'tenant-cafepam-0001',
    tenant_name: 'Café com Pam',
    lead_id: 'lead-cafepam-002',
    lead_name: 'Carla Mendes',
    job_id: 'job-003',
    action: 'schedule',
    channel: 'n8n',
    summary: 'Reunião agendada com Carla Mendes — 30/03 às 14h via Google Calendar',
    created_at: ts(-97),
  },
  {
    id: 'log-005',
    tenant_id: 'tenant-cafepam-0001',
    tenant_name: 'Café com Pam',
    lead_id: 'lead-cafepam-002',
    lead_name: 'Carla Mendes',
    job_id: 'job-003',
    action: 'schedule',
    channel: 'whatsapp',
    summary: 'Confirmação de agendamento enviada para Carla Mendes via WhatsApp',
    created_at: ts(-96),
  },
  {
    id: 'log-006',
    tenant_id: 'tenant-jurema-0001',
    tenant_name: 'Jurema Brokers',
    lead_id: 'lead-jurema-002',
    lead_name: 'Marcos Viana',
    job_id: 'job-004',
    action: 'ai_takeover',
    channel: 'whatsapp',
    summary: 'Agente Luana assumiu conversa com Marcos Viana — interesse em Apto 3Q Manaíra',
    created_at: ts(-87),
  },
  {
    id: 'log-007',
    tenant_id: 'tenant-nexus-0001',
    tenant_name: 'Nexus Consultoria',
    lead_id: 'lead-nexus-001',
    lead_name: 'Pedro Alves',
    job_id: 'job-005',
    action: 'qualify',
    channel: 'system',
    summary: 'Tentativa 3/3 falhou — Evolution API timeout. Job marcado como failed.',
    created_at: ts(-75),
  },
  {
    id: 'log-008',
    tenant_id: 'tenant-jurema-0001',
    tenant_name: 'Jurema Brokers',
    lead_id: 'lead-jurema-001',
    lead_name: 'João Ferreira',
    job_id: null,
    action: 'status_change',
    channel: 'web',
    summary: 'Status de João Ferreira atualizado para "negotiation" por Eric',
    created_at: ts(-70),
  },
  {
    id: 'log-009',
    tenant_id: 'tenant-cafepam-0001',
    tenant_name: 'Café com Pam',
    lead_id: 'lead-cafepam-003',
    lead_name: 'Beatriz Santos',
    job_id: 'job-006',
    action: 'send_proposal',
    channel: 'n8n',
    summary: 'Gerando proposta PDF para Beatriz Santos — projeto de design sala de estar',
    created_at: ts(-58),
  },
  {
    id: 'log-010',
    tenant_id: 'tenant-jurema-0001',
    tenant_name: 'Jurema Brokers',
    lead_id: 'lead-jurema-003',
    lead_name: 'Fernanda Costa',
    job_id: 'job-007',
    action: 'schedule',
    channel: 'n8n',
    summary: 'Agendando visita ao imóvel para Fernanda Costa — Apto 2Q Tambaú',
    created_at: ts(-38),
  },
  {
    id: 'log-011',
    tenant_id: 'tenant-nexus-0001',
    tenant_name: 'Nexus Consultoria',
    lead_id: null,
    lead_name: null,
    job_id: null,
    action: 'provisioning',
    channel: 'system',
    summary: 'CRM Nexus Consultoria em provisionamento — aguardando configuração de pipeline',
    created_at: ts(-35),
  },
  {
    id: 'log-012',
    tenant_id: 'tenant-nexus-0001',
    tenant_name: 'Nexus Consultoria',
    lead_id: 'lead-nexus-002',
    lead_name: 'Ricardo Lima',
    job_id: 'job-008',
    action: 'qualify',
    channel: 'web',
    summary: 'Eric disparou qualificação manual para Ricardo Lima',
    created_at: ts(-20),
  },
  {
    id: 'log-013',
    tenant_id: 'tenant-cafepam-0001',
    tenant_name: 'Café com Pam',
    lead_id: 'lead-cafepam-004',
    lead_name: 'Lucas Rocha',
    job_id: 'job-009',
    action: 'ai_takeover',
    channel: 'web',
    summary: 'Eric ativou IA para assumir lead Lucas Rocha via painel CONTROL',
    created_at: ts(-10),
  },
  {
    id: 'log-014',
    tenant_id: 'tenant-jurema-0001',
    tenant_name: 'Jurema Brokers',
    lead_id: 'lead-jurema-004',
    lead_name: 'Sofia Barbosa',
    job_id: 'job-010',
    action: 'send_proposal',
    channel: 'n8n',
    summary: 'Proposta de financiamento enviada para Sofia Barbosa — Casa em Cabo Branco',
    created_at: ts(-2),
  },
  {
    id: 'log-015',
    tenant_id: 'tenant-jurema-0001',
    tenant_name: 'Jurema Brokers',
    lead_id: 'lead-jurema-004',
    lead_name: 'Sofia Barbosa',
    job_id: 'job-010',
    action: 'send_proposal',
    channel: 'whatsapp',
    summary: 'Sofia Barbosa confirmou recebimento da proposta via WhatsApp',
    created_at: ts(-1),
  },
]

// ─── DASHBOARD DATA ──────────────────────────────────────────────────────────

export const mockControlDashboard: ControlDashboardData = {
  tenants: [tenantCafePam, tenantJurema, tenantNexus],
  recent_jobs: recentJobs,
  recent_logs: recentLogs,
  global_stats: {
    total_tenants: 3,
    active_tenants: 3,
    total_leads: 25,
    total_jobs_today: 18,
    jobs_pending: 2,
    jobs_failed: 1,
  },
}
