import type { Contract } from '@/types/contracts'

// ─── Mock contracts for two tenants ──────────────────────────────────────────
// tenant-cafepam-0001 = Cafe com Pam (design de interiores)
// dev-tenant          = Jurema Brokers (imobiliario)

export const MOCK_CONTRACTS: Contract[] = [
  // ── Jurema Brokers ────────────────────────────────────────────────────────
  {
    id: 'contract-jurema-001',
    tenant_id: 'dev-tenant',
    lead_id: 'lead-jurema-001',
    lead_name: 'Adriana Fontenele',
    project_id: 'imovel-001',
    project_name: 'Apto Vista Mar - Meireles',
    broker_id: 'corretor-luana',
    corretor_name: 'Luana Azevedo',
    type: 'venda',
    status: 'signed',
    value: 320000,
    notes: 'Contrato de compra e venda assinado. Financiamento CEF aprovado.',
    signed_at: '2026-03-10T14:00:00Z',
    expires_at: null,
    created_at: '2026-03-01T08:00:00Z',
    updated_at: '2026-03-10T14:00:00Z',
  },
  {
    id: 'contract-jurema-002',
    tenant_id: 'dev-tenant',
    lead_id: 'lead-jurema-002',
    lead_name: 'Carlos Henrique Lima',
    project_id: 'imovel-002',
    project_name: 'Casa Duplex - Aldeota',
    broker_id: 'corretor-luana',
    corretor_name: 'Luana Azevedo',
    type: 'venda',
    status: 'sent',
    value: 750000,
    notes: 'Aguardando aprovacao do financiamento. Cliente enviou documentacao.',
    signed_at: null,
    expires_at: '2026-04-30T23:59:00Z',
    created_at: '2026-03-15T10:00:00Z',
    updated_at: '2026-03-28T16:00:00Z',
  },
  {
    id: 'contract-jurema-003',
    tenant_id: 'dev-tenant',
    lead_id: 'lead-jurema-003',
    lead_name: 'Patricia Vasconcelos',
    project_id: 'imovel-003',
    project_name: 'Studio Premium - Cocó',
    broker_id: 'corretor-joao',
    corretor_name: 'Joao Melo',
    type: 'locacao',
    status: 'signed',
    value: 3800,
    notes: 'Contrato de locacao 12 meses. Deposito pago.',
    signed_at: '2026-02-20T11:00:00Z',
    expires_at: '2027-02-20T23:59:00Z',
    created_at: '2026-02-10T09:00:00Z',
    updated_at: '2026-02-20T11:00:00Z',
  },
  {
    id: 'contract-jurema-004',
    tenant_id: 'dev-tenant',
    lead_id: 'lead-jurema-004',
    lead_name: 'Marcos Augusto Rocha',
    project_id: 'imovel-004',
    project_name: 'Cobertura Duplex - Papicu',
    broker_id: 'corretor-luana',
    corretor_name: 'Luana Azevedo',
    type: 'venda',
    status: 'sent',
    value: 1250000,
    notes: 'Proposta aceita verbalmente. Aguardando envio dos documentos.',
    signed_at: null,
    expires_at: '2026-04-15T23:59:00Z',
    created_at: '2026-03-20T13:00:00Z',
    updated_at: '2026-03-25T09:00:00Z',
  },
  {
    id: 'contract-jurema-005',
    tenant_id: 'dev-tenant',
    lead_id: 'lead-jurema-005',
    lead_name: 'Fernanda Gomes',
    project_id: 'imovel-005',
    project_name: 'Apto 3 Qts - Eusebio',
    broker_id: 'corretor-joao',
    corretor_name: 'Joao Melo',
    type: 'venda',
    status: 'cancelled',
    value: 280000,
    notes: 'Cliente desistiu — mudou para outro estado.',
    signed_at: null,
    expires_at: null,
    created_at: '2026-02-05T10:00:00Z',
    updated_at: '2026-02-28T14:00:00Z',
  },
  {
    id: 'contract-jurema-006',
    tenant_id: 'dev-tenant',
    lead_id: 'lead-jurema-006',
    lead_name: 'Bruno Cavalcante',
    project_id: 'imovel-006',
    project_name: 'Sala Comercial - Meireles',
    broker_id: 'corretor-luana',
    corretor_name: 'Luana Azevedo',
    type: 'locacao',
    status: 'draft',
    value: 6500,
    notes: 'Rascunho inicial. Negociando termos do contrato.',
    signed_at: null,
    expires_at: null,
    created_at: '2026-04-01T08:00:00Z',
    updated_at: '2026-04-01T08:00:00Z',
  },
  // ── Cafe com Pam ─────────────────────────────────────────────────────────
  {
    id: 'contract-pam-001',
    tenant_id: 'tenant-cafepam-0001',
    lead_id: 'lead-pam-001',
    lead_name: 'Isabela Torres',
    project_id: 'projeto-pam-001',
    project_name: 'Reforma Sala e Dois Quartos',
    broker_id: 'corretor-pam',
    corretor_name: 'Pamela Brandao',
    type: 'servico',
    status: 'signed',
    value: 28000,
    notes: 'Projeto completo sala + 2 quartos. Aprovado e em execucao.',
    signed_at: '2026-03-05T10:00:00Z',
    expires_at: '2026-06-05T23:59:00Z',
    created_at: '2026-02-25T09:00:00Z',
    updated_at: '2026-03-05T10:00:00Z',
  },
  {
    id: 'contract-pam-002',
    tenant_id: 'tenant-cafepam-0001',
    lead_id: 'lead-pam-002',
    lead_name: 'Ricardo Andrade',
    project_id: 'projeto-pam-002',
    project_name: 'Design Escritorio Corporativo',
    broker_id: 'corretor-pam',
    corretor_name: 'Pamela Brandao',
    type: 'servico',
    status: 'sent',
    value: 45000,
    notes: 'Proposta enviada. Cliente avaliando opcoes de financiamento.',
    signed_at: null,
    expires_at: '2026-04-20T23:59:00Z',
    created_at: '2026-03-18T11:00:00Z',
    updated_at: '2026-03-22T15:00:00Z',
  },
  {
    id: 'contract-pam-003',
    tenant_id: 'tenant-cafepam-0001',
    lead_id: 'lead-pam-003',
    lead_name: 'Ana Ligia Saraiva',
    project_id: 'projeto-pam-003',
    project_name: 'Cozinha Planejada + Lavabo',
    broker_id: 'corretor-pam',
    corretor_name: 'Pamela Brandao',
    type: 'servico',
    status: 'draft',
    value: 15500,
    notes: 'Briefing coletado. Aguardando visita tecnica para fechar escopo.',
    signed_at: null,
    expires_at: null,
    created_at: '2026-04-02T09:00:00Z',
    updated_at: '2026-04-02T09:00:00Z',
  },
  {
    id: 'contract-pam-004',
    tenant_id: 'tenant-cafepam-0001',
    lead_id: 'lead-pam-004',
    lead_name: 'Celso Viana',
    project_id: 'projeto-pam-004',
    project_name: 'Consultoria Decoracao',
    broker_id: 'corretor-pam',
    corretor_name: 'Pamela Brandao',
    type: 'parceria',
    status: 'cancelled',
    value: 5000,
    notes: 'Contrato de consultoria expirado sem renovacao.',
    signed_at: '2025-10-15T10:00:00Z',
    expires_at: '2026-01-15T23:59:00Z',
    created_at: '2025-10-01T08:00:00Z',
    updated_at: '2026-01-16T00:01:00Z',
  },
]
